name: Deploy Virtual Network
 
on:

  workflow_dispatch:  # Allows manual trigger from GitHub UI
 
jobs:

  deploy:

    runs-on: ubuntu-latest
 
    steps:

    - name: Checkout code

      uses: actions/checkout@v3
 
    - name: Azure Login

      uses: azure/login@v1

      with:

        creds: ${{ secrets.AZURE_CREDENTIALS }}
 
    - name: Deploy ARM Template

      uses: azure/arm-deploy@v1

      with:

        resourceGroupName: "Yerramala-VMResourcegroup"

        template: ./vnet.json

        deploymentName: github-deployment
 
 
 